spring.application.name=java

# Definindo a porta do servidor 8082
server.port=8082 
# Definindo a URL do banco de dados e algumas configurações pro H2
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver=org.h2.Driver
# Usuario para entrar no banco de dados
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Configurações do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.h2.console.enabled=true



